apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arma-reforger.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arma-reforger.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  armarserver.server.json: |-
    {
        "dedicatedServerId": {{ .Values.config.dedicatedServerID | quote }},
        "region": {{ .Values.config.region | quote }},
        "bindAddress": {{ .Values.config.gameHostBindAddress | quote }},
        "bindPort": {{ .Values.config.gameHostBindPort }},
        "publicAddress": {{ .Values.config.gameHostRegisterBindAddress | quote }},
        "publicPort": {{ .Values.config.gameHostRegisterBindPort }},
        "game.name": {{ .Values.config.name | quote }},
        "game.password": {{ include "serverPassword" . | quote }},
        "game.passwordAdmin": {{ .Values.credentials.adminPassword | quote }},
        "game.scenarioId": {{ .Values.config.scenarioID | quote }},
        "game.maxPlayers": {{ .Values.config.playerCountLimit }},
        "game.gameProperties.fastValidation": true,
        "a2sQueryEnabled": true,
        "steamQueryPort": {{ .Values.config.steamQueryPort }}
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arma-reforger.fullname" . }}-common
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arma-reforger.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  common.cfg: |-
    ## Server Config
    {{- if .Values.config.serverConfigPath }}
    servercfgfullpath={{ .Values.config.serverConfigPath | quote }}
    {{- end }}

    {{- if .Values.config.startParameters }}
    startparameters="-config ${servercfgfullpath} -profile ${serverprofilefullpath} -maxFPS ${maxfps} {{ .Values.config.startParameters }}"
    {{- end }}

    {{- if .Values.config.commonConfigPath }}
    commoncfgfullpath={{ .Values.config.commonConfigPath | quote }}
    {{- end }}

    {{- if .Values.config.maxFPS }}
    maxfps={{ .Values.config.maxFPS | quote }}
    {{- end }}

    ## Discord webhook alerts
    {{- if .Values.alerts.discord }}
    discordalert="on"
    discordwebhook={{ .Values.alerts.discord | quote }}
    {{- end }}
