apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arma-reforger.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arma-reforger.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  armarserver.server.json: |-
    {
        "bindAddress": "0.0.0.0",
        "bindPort": 2001,
        "publicAddress": "",
        "publicPort": 32001,
        "region": "RU",
        "game": {
            "name": "SIBERIA Official Scenarios",
            "password": "",
            "passwordAdmin": "323131",
            "scenarioId": "{DFAC5FABD11F2390}Missions/26_CombatOpsEveron.conf",
            "maxPlayers": 64,
            "visible": true,
            "crossPlatform": true,
            "supportedPlatforms": [
                "PLATFORM_PC",
                "PLATFORM_XBL",
                "PLATFORM_PSN"
            ],
            "modsRequiredByDefault": true,
            "gameProperties": {
                "serverMaxViewDistance": 5000,
                "networkViewDistance": 5000,
                "disableThirdPerson": false,
                "fastValidation": true,
                "battlEye": true,
                "VONDisableUI": false,
                "VONDisableDirectSpeechUI": false,
                "VONCanTransmitCrossFaction": false,
                "missionHeader": {
                    "m_sName": "Arma Reforger Server"
                }
            }
        },
        "a2s": {
            "address": "0.0.0.0",
            "port": 17777
        },
        "operating": {
            "disableCrashReporter": true
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arma-reforger.fullname" . }}-common
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arma-reforger.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  common.cfg: |-
    ## Server Config
    {{- if .Values.config.serverConfigPath }}
    servercfgfullpath={{ .Values.config.serverConfigPath | quote }}
    {{- end }}

    {{- if .Values.config.startParameters }}
    startparameters="-config ${servercfgfullpath} -profile ${serverprofilefullpath} -maxFPS ${maxfps} {{ .Values.config.startParameters }}"
    {{- end }}

    {{- if .Values.config.commonConfigPath }}
    commoncfgfullpath={{ .Values.config.commonConfigPath | quote }}
    {{- end }}

    {{- if .Values.config.maxFPS }}
    maxfps={{ .Values.config.maxFPS | quote }}
    {{- end }}

    ## Discord webhook alerts
    {{- if .Values.alerts.discord }}
    discordalert="on"
    discordwebhook={{ .Values.alerts.discord | quote }}
    {{- end }}
